name: CI (Julia 1.6-nightly)
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  CI-julia-1-6-nightly:
    name: CI-julia-1-6-nightly
    runs-on: ubuntu-latest
    container:
      image: fluxrm/flux-core:focal
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6-nightly'
        arch:
          - x64
    steps:
      - name: Installing dependencies...
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - uses: actions/checkout@v1
      - name: Setup Julia
        run: |
          wget -qO - "https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.0-rc1-linux-x86_64.tar.gz" | sudo tar xzf - -C /usr/local --strip-components=1
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Julia test
        run: |
          julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
          julia --project=test --color=yes --check-bounds=yes --code-coverage=user --depwarn=yes test/runtests.jl
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
